import 'wikipedia_tips.dart';

// Regional tips reviewed against official municipal pages; sources below.
// Population information is excluded.
const regionalTips = <Map<String, String>>[
  {
    "id": "29202:public:1",
    "cityId": "29202",
    "category": "歴史",
    "text": "大和高田市の高田川の桜は、1948年の市制施行を記念した市民の植樹です。",
    "source": "https://www.city.yamatotakada.nara.jp/kanko/index.html",
  },
  {
    "id": "29202:public:2",
    "cityId": "29202",
    "category": "歴史",
    "text": "大和高田市の専立寺は「高田御坊」とも呼ばれ、寺内町の街並みが残ります。",
    "source": "https://www.city.yamatotakada.nara.jp/kanko/index.html",
  },
  {
    "id": "29205:public:3",
    "cityId": "29205",
    "category": "文化財",
    "text": "橿原市の今井町は戦国時代にできた寺内町で、江戸時代の町並みが残っています。",
    "source":
        "https://www.city.kashihara.nara.jp/kanko_bunka_sports/kanko/index.html",
  },
  {
    "id": "29205:public:4",
    "cityId": "29205",
    "category": "文化財",
    "text": "橿原市の今井町は、1993年に重要伝統的建造物群保存地区となりました。",
    "source":
        "https://www.city.kashihara.nara.jp/kanko_bunka_sports/kanko/index.html",
  },
  {
    "id": "29208:public:5",
    "cityId": "29208",
    "category": "文化財",
    "text": "御所市の條ウル神古墳は、巨大な横穴式石室と刳抜式の家形石棺を備えています。",
    "source": "https://www.city.gose.nara.jp/0000004750.html",
  },
  {
    "id": "29209:public:6",
    "cityId": "29209",
    "category": "伝統工芸",
    "text": "生駒の高山茶筌は、室町時代に鷹山氏の宗砌が考案したと伝わります。",
    "source": "https://www.city.ikoma.lg.jp/0000002188.html",
  },
  {
    "id": "29209:public:7",
    "cityId": "29209",
    "category": "歴史",
    "text": "生駒市の竹林寺の境内には、行基の墓があります。",
    "source": "https://www.city.ikoma.lg.jp/0000002188.html",
  },
  {
    "id": "29211:public:8",
    "cityId": "29211",
    "category": "文化財",
    "text": "葛城市の當麻寺は、国宝の當麻曼荼羅など多くの文化財を伝えています。",
    "source": "https://www.city.katsuragi.nara.jp/shisei/shinoshokai/3700.html",
  },
  {
    "id": "29211:public:9",
    "cityId": "29211",
    "category": "文化財",
    "text": "葛城市には、日本最古の官道として紹介される竹内街道があります。",
    "source": "https://www.city.katsuragi.nara.jp/shisei/shinoshokai/3700.html",
  },
  {
    "id": "29344:public:10",
    "cityId": "29344",
    "category": "地理",
    "text": "斑鳩町の南には大和川、東には富雄川、西には竜田川が流れています。",
    "source": "https://www.town.ikaruga.nara.jp/0000000343.html",
  },
  {
    "id": "29345:public:11",
    "cityId": "29345",
    "category": "歴史",
    "text": "安堵町の太子道は、聖徳太子が飛鳥と法隆寺を往復した道と伝わります。",
    "source": "https://www.town.ando.nara.jp/0000002093.html",
  },
  {
    "id": "29362:public:12",
    "cityId": "29362",
    "category": "歴史",
    "text": "三宅町は、社会福祉事業の先駆者として知られる忍性菩薩の生誕の地です。",
    "source": "https://www.town.miyake.lg.jp/site/executives/",
  },
  {
    "id": "29424:public:13",
    "cityId": "29424",
    "category": "地理",
    "text": "上牧町は、西側を葛下川、中央を滝川が流れ、豆山や丘陵地帯が広がる町です。",
    "source": "https://www.town.kanmaki.nara.jp/city/1091.html",
  },
  {
    "id": "29424:public:14",
    "cityId": "29424",
    "category": "地理",
    "text": "上牧町の面積は6.14km²。東西2.1km、南北3.6kmのほぼ長方形です。",
    "source": "https://www.town.kanmaki.nara.jp/city/1091.html",
  },
  {
    "id": "29426:public:15",
    "cityId": "29426",
    "category": "文化財",
    "text": "広陵町は、特別史跡「巣山古墳」から出土した遺物の三次元データを公開しています。",
    "source":
        "https://www.town.koryo.nara.jp/category/18-1-0-0-0-0-0-0-0-0.html",
  },
  {
    "id": "29427:public:16",
    "cityId": "29427",
    "category": "農業",
    "text": "河合町の大規模なぶどう園づくりは、町の開拓事業とともに大正時代に始まりました。",
    "source": "https://www.town.kawai.nara.jp/chosei/purofuru/2990.html",
  },
  {
    "id": "29442:public:17",
    "cityId": "29442",
    "category": "特産品",
    "text": "大淀町の大阿太高原では、1902年ごろから二十世紀梨の栽培が始まりました。",
    "source": "https://www.town.oyodo.lg.jp/0000000332.html",
  },
  {
    "id": "29443:public:18",
    "cityId": "29443",
    "category": "伝統工芸",
    "text": "下市町の割り箸には、吉野杉の美しい木目が生かされています。",
    "source": "https://www.town.shimoichi.lg.jp/0000000272.html",
  },
  {
    "id": "29443:public:19",
    "cityId": "29443",
    "category": "伝統工芸",
    "text": "下市町の三宝・神具づくりは、吉野ヒノキを加工する伝統産業です。",
    "source": "https://www.town.shimoichi.lg.jp/0000000272.html",
  },
  {
    "id": "29443:public:20",
    "cityId": "29443",
    "category": "伝統工芸",
    "text": "下市町の焼杉杢目彫は、吉野杉を彫り、焼いてから丹念に磨いて作られます。",
    "source": "https://www.town.shimoichi.lg.jp/0000000272.html",
  },
  {
    "id": "29443:public:21",
    "cityId": "29443",
    "category": "農業",
    "text": "下市町の栃原地域は柿の名産地で、柿の葉寿司に使う葉も生産しています。",
    "source": "https://www.town.shimoichi.lg.jp/0000000272.html",
  },
  {
    "id": "29443:public:22",
    "cityId": "29443",
    "category": "歴史",
    "text": "下市町は、室町時代に建立された願行寺の寺内町として発展しました。",
    "source": "https://www.town.shimoichi.lg.jp/0000000246.html",
  },
  {
    "id": "29443:public:23",
    "cityId": "29443",
    "category": "歴史",
    "text": "浄瑠璃や歌舞伎の「義経千本櫻」に登場する「すしやの段」は、下市が舞台です。",
    "source": "https://www.town.shimoichi.lg.jp/0000000246.html",
  },
  {
    "id": "29444:public:24",
    "cityId": "29444",
    "category": "文化財",
    "text": "黒滝村には、世界文化遺産「紀伊山地の霊場と参詣道」の大峯奥駈道の一部があります。",
    "source": "https://www.vill.kurotaki.nara.jp/kankoguide/",
  },
  {
    "id": "29446:public:25",
    "cityId": "29446",
    "category": "自然",
    "text": "天川村は、面積の約4分の1が吉野熊野国立公園に指定されています。",
    "source": "https://www.vill.tenkawa.nara.jp/",
  },
  {
    "id": "29446:public:26",
    "cityId": "29446",
    "category": "地理",
    "text": "天川村は大峯山系の山々に囲まれ、谷間の集落は標高441～820mにあります。",
    "source": "https://www.vill.tenkawa.nara.jp/tourism/history/",
  },
  {
    "id": "29446:public:27",
    "cityId": "29446",
    "category": "自然",
    "text": "天川村の来迎院にあるイチョウは、奈良県指定天然記念物に指定されています。",
    "source":
        "https://www.vill.tenkawa.nara.jp/tourism/modelcourse/giant_tree/",
  },
  {
    "id": "29447:public:28",
    "cityId": "29447",
    "category": "歴史",
    "text": "野迫川村の荒神社は、弘法大師が高野山を開く際に勧請したとされる神社です。",
    "source": "https://www.vill.nosegawa.nara.jp/top/tourism/288.html",
  },
  {
    "id": "29449:public:29",
    "cityId": "29449",
    "category": "地理",
    "text": "十津川村は奈良県の最南端にあり、西は和歌山県、東は三重県に接しています。",
    "source": "https://www.vill.totsukawa.lg.jp/about/village/",
  },
  {
    "id": "29449:public:30",
    "cityId": "29449",
    "category": "地理",
    "text": "十津川村の面積は672.38km²。日本の施政下で最も広い村です。",
    "source": "https://www.vill.totsukawa.lg.jp/about/village/",
  },
  {
    "id": "29450:public:31",
    "cityId": "29450",
    "category": "特産品",
    "text": "下北山村の「下北春まな」は、伝統野菜の「大和野菜」に選ばれています。",
    "source": "https://www.vill.shimokitayama.nara.jp/kankou/tokusanhin.html",
  },
  {
    "id": "29450:public:32",
    "cityId": "29450",
    "category": "特産品",
    "text": "下北山村のめはり寿司は、下北春まなの漬物を使う山仕事の弁当でした。",
    "source": "https://www.vill.shimokitayama.nara.jp/kankou/tokusanhin.html",
  },
  {
    "id": "29450:public:33",
    "cityId": "29450",
    "category": "特産品",
    "text": "下北山村の「天削箸」は、吉野杉を加工するときに出る廃材を再利用して作られます。",
    "source": "https://www.vill.shimokitayama.nara.jp/kankou/tokusanhin.html",
  },
  {
    "id": "29450:public:34",
    "cityId": "29450",
    "category": "特産品",
    "text": "下北山村茶は、5月ごろに採れる一番茶の新芽を手で摘み、炒って番茶にしたものです。",
    "source": "https://www.vill.shimokitayama.nara.jp/kankou/tokusanhin.html",
  },
  {
    "id": "29202:organized:003",
    "cityId": "29202",
    "category": "伝統行事",
    "text": "大和高田市の捨篠池では、7月7日に吉野の蛙とびと連携した蓮華会を開催。",
    "source": "https://www.city.yamatotakada.nara.jp/kanko/index.html",
  },
  {
    "id": "29202:organized:005",
    "cityId": "29202",
    "category": "地理",
    "text": "大和高田市は奈良県の北西部に位置し、大阪との文化・経済の結び付きが深い地域です。",
    "source": "https://www.city.yamatotakada.nara.jp/kanko/index.html",
  },
  {
    "id": "29205:organized:006",
    "cityId": "29205",
    "category": "歴史",
    "text": "橿原市には、古代の都「藤原京」の跡があります。",
    "source":
        "https://www.city.kashihara.nara.jp/kanko_bunka_sports/kanko/index.html",
  },
  {
    "id": "29208:organized:015",
    "cityId": "29208",
    "category": "地理",
    "text": "御所市は大和平野の西南部にあり、金剛山・葛城山の山麓から平野が広がっています。",
    "source": "https://www.city.gose.nara.jp/kankou/index.html",
  },
  {
    "id": "29209:organized:018",
    "cityId": "29209",
    "category": "地域文化",
    "text": "生駒市のイメージキャラクターは「たけまるくん」です。",
    "source": "https://www.city.ikoma.lg.jp/0000002188.html",
  },
  {
    "id": "29209:organized:020",
    "cityId": "29209",
    "category": "歴史",
    "text": "生駒市の長福寺は、聖徳太子の開基と市の歴史紹介で伝えられています。",
    "source": "https://www.city.ikoma.lg.jp/0000002188.html",
  },
  {
    "id": "29209:organized:022",
    "cityId": "29209",
    "category": "歴史",
    "text": "中世の生駒では山岳宗教や地蔵信仰が広まり、八大竜王や石仏がまつられました。",
    "source": "https://www.city.ikoma.lg.jp/0000002188.html",
  },
  {
    "id": "29209:organized:024",
    "cityId": "29209",
    "category": "歴史",
    "text": "江戸時代の生駒では、郡山藩領と旗本領が交錯し、乙田には天領もありました。",
    "source": "https://www.city.ikoma.lg.jp/0000002188.html",
  },
  {
    "id": "29209:organized:025",
    "cityId": "29209",
    "category": "歴史",
    "text": "生駒市の宝山寺は、1678年に僧・湛海が開いたと伝えられています。",
    "source": "https://www.city.ikoma.lg.jp/0000002188.html",
  },
  {
    "id": "29211:organized:028",
    "cityId": "29211",
    "category": "地理",
    "text": "葛城市の公式紹介に掲載された面積は33.72km²です。",
    "source": "https://www.city.katsuragi.nara.jp/shisei/shinoshokai/3700.html",
  },
  {
    "id": "29211:organized:029",
    "cityId": "29211",
    "category": "地理",
    "text": "葛城市は金剛・葛城・二上の山並みと、東側に広がる沖積地から成る町です。",
    "source": "https://www.city.katsuragi.nara.jp/shisei/shinoshokai/3700.html",
  },
  {
    "id": "29344:organized:032",
    "cityId": "29344",
    "category": "文化財",
    "text": "斑鳩町には、法隆寺のほか藤ノ木古墳などの歴史文化遺産があります。",
    "source": "https://www.town.ikaruga.nara.jp/0000000343.html",
  },
  {
    "id": "29345:organized:034",
    "cityId": "29345",
    "category": "地理",
    "text": "安堵町は、奈良市から直線で約10km強、大阪市から約30kmです。",
    "source": "https://www.town.ando.nara.jp/0000002093.html",
  },
  {
    "id": "29362:organized:036",
    "cityId": "29362",
    "category": "地理",
    "text": "三宅町は、町の公式紹介で奈良県内で最も面積の小さな町と紹介されています。",
    "source": "https://www.town.miyake.lg.jp/site/executives/",
  },
  {
    "id": "29402:organized:038",
    "cityId": "29402",
    "category": "文化財",
    "text": "明日香村の飛鳥寺西側には、遺跡や入鹿の首塚を紹介する方位盤があります。",
    "source": "https://www.asukamura.jp/sekaiisan-tomoni/news_260611.html",
  },
  {
    "id": "29424:organized:044",
    "cityId": "29424",
    "category": "歴史",
    "text": "上牧町の片岡城は、1574年に松永久秀の軍勢に攻め落とされました。",
    "source": "https://www.town.kanmaki.nara.jp/city/1091.html",
  },
  {
    "id": "29427:organized:048",
    "cityId": "29427",
    "category": "地理",
    "text": "河合町は奈良盆地の西部、馬見丘陵の北東部に位置しています。",
    "source": "https://www.town.kawai.nara.jp/chosei/purofuru/2990.html",
  },
  {
    "id": "29427:organized:049",
    "cityId": "29427",
    "category": "歴史",
    "text": "河合町では、約1万5千年前の旧石器時代の暮らしの痕跡が見られます。",
    "source": "https://www.town.kawai.nara.jp/chosei/purofuru/2990.html",
  },
  {
    "id": "29427:organized:051",
    "cityId": "29427",
    "category": "歴史",
    "text": "河合町を流れる大和川は、古くから物資を運ぶ水路として利用されてきました。",
    "source": "https://www.town.kawai.nara.jp/kanko/sansaku/5904.html",
  },
  {
    "id": "29442:organized:053",
    "cityId": "29442",
    "category": "自然",
    "text": "大淀町の町の木は、ブナ科のアラカシです。",
    "source": "https://www.town.oyodo.lg.jp/0000000332.html",
  },
  {
    "id": "29443:organized:055",
    "cityId": "29443",
    "category": "伝統工芸",
    "text": "下市では南北朝時代、里人が後醍醐天皇へ杉箸を献上したと伝わります。",
    "source": "https://www.town.shimoichi.lg.jp/0000000272.html",
  },
  {
    "id": "29443:organized:058",
    "cityId": "29443",
    "category": "伝統工芸",
    "text": "下市の吉野杉製の桶は、江戸時代中期以降、伊丹・灘・伏見の酒器に使われました。",
    "source": "https://www.town.shimoichi.lg.jp/0000000272.html",
  },
  {
    "id": "29443:organized:061",
    "cityId": "29443",
    "category": "歴史",
    "text": "下市町阿知賀の百合ケ峯などの遺跡では、縄文時代の遺物が発見されています。",
    "source": "https://www.town.shimoichi.lg.jp/0000000246.html",
  },
  {
    "id": "29443:organized:063",
    "cityId": "29443",
    "category": "文化財",
    "text": "下市町阿知賀の岡峯古墳は、玄室に石棚を持つ珍しい古墳です。",
    "source": "https://www.town.shimoichi.lg.jp/0000000246.html",
  },
  {
    "id": "29443:organized:064",
    "cityId": "29443",
    "category": "歴史",
    "text": "下市町の丹生川上神社下社は、天武年間に創祀されたと伝わります。",
    "source": "https://www.town.shimoichi.lg.jp/0000000246.html",
  },
  {
    "id": "29443:organized:065",
    "cityId": "29443",
    "category": "歴史",
    "text": "下市は吉野の森林資源を商う市場町として発展し、かつては月6回の市を開催。",
    "source": "https://www.town.shimoichi.lg.jp/0000000246.html",
  },
  {
    "id": "29443:organized:066",
    "cityId": "29443",
    "category": "歴史",
    "text": "16世紀の下市では、初期の商業手形「下市札」が発行されました。",
    "source": "https://www.town.shimoichi.lg.jp/0000000246.html",
  },
  {
    "id": "29443:organized:067",
    "cityId": "29443",
    "category": "伝統行事",
    "text": "下市蛭子神社では、毎年2月12日に昔の市の名残である「初市」が開かれます。",
    "source": "https://www.town.shimoichi.lg.jp/0000000246.html",
  },
  {
    "id": "29444:organized:070",
    "cityId": "29444",
    "category": "自然",
    "text": "黒滝村の赤岩渓谷近くでは、春に枝垂れ桜が見られます。",
    "source": "https://www.vill.kurotaki.nara.jp/kankoguide/",
  },
  {
    "id": "29446:organized:073",
    "cityId": "29446",
    "category": "歴史",
    "text": "天川村の大峯山は、役行者の開山以来、修験道の修行の場となっています。",
    "source": "https://www.vill.tenkawa.nara.jp/",
  },
  {
    "id": "29446:organized:074",
    "cityId": "29446",
    "category": "地域施設",
    "text": "天川村の洞川温泉ビジターセンターは、吉野杉を使った建物とヒノキの浴槽が特徴です。",
    "source": "https://www.vill.tenkawa.nara.jp/tourism/",
  },
  {
    "id": "29446:organized:075",
    "cityId": "29446",
    "category": "地域施設",
    "text": "天川村の天の川温泉センターは、玄関正面にカエデの大木の柱を使っています。",
    "source": "https://www.vill.tenkawa.nara.jp/tourism/",
  },
  {
    "id": "29446:organized:076",
    "cityId": "29446",
    "category": "特産品",
    "text": "天川村の「みずはの湯」では、特産のトウキなどを使った薬湯を楽しめます。",
    "source": "https://www.vill.tenkawa.nara.jp/tourism/",
  },
  {
    "id": "29446:organized:078",
    "cityId": "29446",
    "category": "歴史",
    "text": "平安時代の天川では、藤原道長をはじめとする人々が御岳詣を行いました。",
    "source": "https://www.vill.tenkawa.nara.jp/tourism/history/",
  },
  {
    "id": "29446:organized:079",
    "cityId": "29446",
    "category": "歴史",
    "text": "天川村は南朝の重要拠点で、課役を免除する綸旨が残されています。",
    "source": "https://www.vill.tenkawa.nara.jp/tourism/history/",
  },
  {
    "id": "29446:organized:080",
    "cityId": "29446",
    "category": "自然",
    "text": "天川村の水分神社には、3本が合体して1本になった杉の巨木があります。",
    "source":
        "https://www.vill.tenkawa.nara.jp/tourism/modelcourse/giant_tree/",
  },
  {
    "id": "29447:organized:084",
    "cityId": "29447",
    "category": "自然",
    "text": "野迫川村は急峻で標高が高く、冬は寒冷で雪が多く、夏は冷涼な地域です。",
    "source": "https://www.vill.nosegawa.nara.jp/tourist_guide/index.html",
  },
  {
    "id": "29449:organized:089",
    "cityId": "29449",
    "category": "自然",
    "text": "十津川村には、源泉かけ流しの温泉や清流、滝、吊り橋があります。",
    "source": "https://www.vill.totsukawa.lg.jp/about/village/",
  },
  {
    "id": "29449:organized:090",
    "cityId": "29449",
    "category": "自然",
    "text": "十津川村では、標高差によって地域ごとに気温が異なります。",
    "source": "https://www.vill.totsukawa.lg.jp/about/village/",
  },
  {
    "id": "29449:organized:091",
    "cityId": "29449",
    "category": "歴史",
    "text": "江戸時代の十津川郷の村々は、1585年の検地から成立したと考えられています。",
    "source": "https://www.vill.totsukawa.lg.jp/about/history/",
  },
  {
    "id": "29449:organized:092",
    "cityId": "29449",
    "category": "歴史",
    "text": "十津川は、明治6年（1873年）の地租法改正によって有租地となりました。",
    "source": "https://www.vill.totsukawa.lg.jp/about/history/",
  },
  {
    "id": "29450:organized:097",
    "cityId": "29450",
    "category": "歴史",
    "text": "下北山村には、南朝の遺臣が大峯・大台を越えて住み着いたと伝わります。",
    "source": "https://www.vill.shimokitayama.nara.jp/kankou/tokusanhin.html",
  },
  {
    "id": "29450:organized:101",
    "cityId": "29450",
    "category": "農業",
    "text": "下北山村では、寒暖差と冷涼な気候を生かし、古くから家庭で茶を作っています。",
    "source": "https://www.vill.shimokitayama.nara.jp/kankou/tokusanhin.html",
  },
  {
    "id": "29450:organized:104",
    "cityId": "29450",
    "category": "木工",
    "text": "下北山村では、杉の間伐材を使った木製遊具が作られています。",
    "source": "https://www.vill.shimokitayama.nara.jp/kankou/tokusanhin.html",
  },
  {
    "id": "29206:sakurai:city-tree",
    "cityId": "29206",
    "category": "自然",
    "text": "桜井市の市の木は「杉」。市内で造林され、木材のまちとしての桜井を象徴しています。",
    "source":
        "https://www.city.sakurai.lg.jp/sosiki/koushitsu/gyouseikeieika/shinogaiyou/sinosyoukai/1393822865729.html",
  },
  {
    "id": "29206:sakurai:city-flower",
    "cityId": "29206",
    "category": "自然",
    "text": "桜井市の市の花は「山ざくら」です。",
    "source":
        "https://www.city.sakurai.lg.jp/sosiki/koushitsu/gyouseikeieika/shinogaiyou/sinosyoukai/1393822865729.html",
  },
  {
    "id": "29206:sakurai:timber",
    "cityId": "29206",
    "category": "産業",
    "text": "桜井市は近代に交通が発達すると、木材の集散と加工のまちとして発展しました。",
    "source":
        "https://www.city.sakurai.lg.jp/sosiki/koushitsu/gyouseikeieika/shinogaiyou/sinosyoukai/1393822398366.html",
  },
  {
    "id": "29206:sakurai:basin",
    "cityId": "29206",
    "category": "地理",
    "text": "桜井市は奈良盆地の中央東南部に位置し、三輪・巻向・初瀬の山々が連なっています。",
    "source":
        "https://www.city.sakurai.lg.jp/sosiki/koushitsu/gyouseikeieika/shinogaiyou/sinosyoukai/1393822398366.html",
  },
  {
    "id": "29206:sakurai:river",
    "cityId": "29206",
    "category": "地理",
    "text": "桜井市には初瀬川のほか、粟原川・寺川・米川・巻向川が流れています。",
    "source":
        "https://www.city.sakurai.lg.jp/sosiki/koushitsu/gyouseikeieika/shinogaiyou/sinosyoukai/1393822398366.html",
  },
  {
    "id": "29206:sakurai:mountains",
    "cityId": "29206",
    "category": "地理",
    "text": "桜井市の2024年更新の市の概要によると、市域の約60％は山間部です。",
    "source":
        "https://www.city.sakurai.lg.jp/sosiki/koushitsu/gyouseikeieika/shinogaiyou/sinosyoukai/1393822398366.html",
  },
  {
    "id": "29206:sakurai:area",
    "cityId": "29206",
    "category": "地理",
    "text": "桜井市の2024年更新の市の概要に掲載された面積は98.91km²です。",
    "source":
        "https://www.city.sakurai.lg.jp/sosiki/koushitsu/gyouseikeieika/shinogaiyou/sinosyoukai/1393822398366.html",
  },
  {
    "id": "29206:sakurai:makimuku",
    "cityId": "29206",
    "category": "歴史",
    "text": "桜井市の纒向では、3～4世紀に大集落が築かれました。",
    "source":
        "https://www.city.sakurai.lg.jp/sosiki/koushitsu/gyouseikeieika/shinogaiyou/sinosyoukai/1393822398366.html",
  },
  {
    "id": "29206:sakurai:daifuku",
    "cityId": "29206",
    "category": "歴史",
    "text": "桜井市の大福遺跡や芝遺跡は、銅鐸の出土で知られる弥生時代の大規模な集落遺跡です。",
    "source":
        "https://www.city.sakurai.lg.jp/sosiki/koushitsu/gyouseikeieika/shinogaiyou/sinosyoukai/1393822398366.html",
  },
  {
    "id": "29206:sakurai:tsuchibutai",
    "cityId": "29206",
    "category": "文化",
    "text": "桜井市の土舞台は、聖徳太子が少年に伎楽を習わせた地と伝わります。",
    "source":
        "https://www.city.sakurai.lg.jp/sosiki/koushitsu/gyouseikeieika/shinogaiyou/public/1391647255137.html",
  },
  {
    "id": "29206:sakurai:sumo",
    "cityId": "29206",
    "category": "歴史",
    "text": "桜井市のカタヤケシは、当麻蹴速と野見宿祢の天覧相撲の地と伝わります。",
    "source":
        "https://www.city.sakurai.lg.jp/sosiki/koushitsu/gyouseikeieika/shinogaiyou/public/1391652430474.html",
  },
  {
    "id": "29206:sakurai:asakura",
    "cityId": "29206",
    "category": "文学",
    "text": "桜井市黒崎は泊瀬朝倉宮の伝承地。雄略天皇に帰される歌が万葉集の第1首です。",
    "source":
        "https://www.city.sakurai.lg.jp/sosiki/koushitsu/gyouseikeieika/shinogaiyou/public/1391655115302.html",
  },
  ...wikipediaTips,
];
