#!/usr/bin/env python3
"""Generate app tips from reviewed Wikipedia summaries (no runtime network).

Usage: python tools/import_wikipedia_tips.py [--check]
Source revisions and attribution live in data/tips/wikipedia_sources.json.
"""
import argparse
from collections import Counter
import json
from pathlib import Path
import re
from urllib.parse import urlparse, parse_qs

ROOT = Path(__file__).resolve().parents[1]


def generate():
    cities = {c['id'] for c in json.loads((ROOT / 'assets/data/nara.json').read_text())['cities']}
    sources = json.loads((ROOT / 'data/tips/wikipedia_sources.json').read_text())
    existing = (ROOT / 'lib/regional_tips.dart').read_text()
    counts = Counter(re.findall(r'"cityId": "(\d+)"', existing))
    texts = set(re.findall(r'"text": "([^"]+)"', existing))
    entries = []
    city = None
    for line_number, line in enumerate((ROOT / 'data/tips/wikipedia.tsv').read_text().splitlines(), 1):
        if not line or line.startswith('#'):
            continue
        if line.startswith('@'):
            city = line[1:]
            if city not in cities:
                raise ValueError(f'Unknown municipality on line {line_number}: {city}')
            continue
        fields = line.split('\t')
        if city is None or len(fields) != 4:
            raise ValueError(f'Invalid row on line {line_number}')
        category, text, source_key, identifier = fields
        source = sources[source_key]
        if not re.fullmatch(rf'{city}:wikipedia:[0-9a-f]{{12}}', identifier):
            raise ValueError(f'Invalid fixed ID on line {line_number}')
        url = urlparse(source['revisionUrl'])
        if url.scheme != 'https' or url.netloc != 'ja.wikipedia.org' or not parse_qs(url.query).get('oldid'):
            raise ValueError(f'Missing Wikipedia revision on line {line_number}')
        if not category or not text or len(text) > 40 or '人口' in text or text in texts:
            raise ValueError(f'Invalid or duplicated tip on line {line_number}: {text}')
        texts.add(text)
        counts[city] += 1
        entries.append({
            'id': identifier,
            'cityId': city,
            'category': category,
            'text': text,
            'source': source['revisionUrl'],
        })
    if set(counts) != cities or any(count != 30 for count in counts.values()):
        raise ValueError(f'Expected 30 tips for every municipality: {dict(counts)}')
    if len({e['id'] for e in entries}) != len(entries):
        raise ValueError('Duplicate IDs')
    out = ['// Generated by tools/import_wikipedia_tips.py; edit data/tips/wikipedia.tsv.',
           '// Adapted from Japanese Wikipedia contributors, CC BY-SA 4.0.',
           '// https://creativecommons.org/licenses/by-sa/4.0/',
           '// Each source URL identifies the reviewed revision and its contributors.',
           'const wikipediaTips = <Map<String, String>>[']
    for entry in entries:
        out.append('  {')
        for key, value in entry.items():
            encoded = json.dumps(value, ensure_ascii=False).replace('$', r'\$')
            out.append(f'    "{key}": {encoded},')
        out.append('  },')
    out.append('];')
    return '\n'.join(out) + '\n', len(entries)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check generated content without modifying it')
    args = parser.parse_args()
    output, count = generate()
    target = ROOT / 'lib/wikipedia_tips.dart'
    if args.check:
        # dart format may wrap long map values; compare the map data, not whitespace.
        def values(s):
            return re.findall(r'"(?:[^"\\]|\\.)*"', s)
        if not target.exists() or values(target.read_text()) != values(output):
            raise SystemExit('Generated tips are stale; run this script then dart format.')
    else:
        target.write_text(output)
    print(f'{count} Wikipedia tips + 90 existing tips: 39 municipalities × 30 = 1170')
